# Generated by Django 6.0 on 2025-12-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book', 'status', 'due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
